-- ============================================================
-- Sistema Inteligente de Gestión de Extintores
-- Esquema para Supabase (Postgres)
-- Ejecutar en: Supabase Dashboard → SQL Editor → New query
-- ============================================================

create table if not exists usuarios (
  id bigint generated by default as identity primary key,
  nombre text not null,
  username text unique not null,
  password_hash text not null,
  password_salt text not null,
  rol text not null check (rol in ('Inspector', 'Responsable', 'Administrador')),
  iniciales text not null,
  creado_en timestamptz not null default now()
);

-- Ubicación como texto libre: el usuario la escribe según sus necesidades,
-- ya no está limitada a una lista fija (antes tabla "ubicaciones" con FK).
create table if not exists extintores (
  id bigint generated by default as identity primary key,
  codigo text unique not null,
  tipo_agente text not null check (tipo_agente in ('PQS-ABC', 'CO2', 'Agua', 'Espuma AFFF', 'K')),
  capacidad text not null,
  ubicacion_nombre text not null,
  ubicacion_area text,
  ubicacion_piso text,
  fecha_recarga date not null,
  fecha_vencimiento date not null,
  fecha_prueba_hidrostatica date not null,
  estado_manual text,
  foto_base64 text,
  qr_svg text,                          -- código QR generado en el servidor (SVG como texto), guardado aquí
  creado_en timestamptz not null default now()
);

create table if not exists inspecciones (
  id bigint generated by default as identity primary key,
  extintor_id bigint not null references extintores(id) on delete cascade,
  usuario_id bigint not null references usuarios(id),
  fecha date not null,
  resultado text not null check (resultado in ('Aprobado', 'Rechazado')),
  presion_ok boolean not null,
  precinto_ok boolean not null,
  senaletica_ok boolean not null,
  observaciones text,
  firma_base64 text,
  origen text not null default 'online',
  creado_en timestamptz not null default now()
);

-- Tabla de solo inserción: no hay endpoints de UPDATE/DELETE sobre ella en el backend.
create table if not exists auditoria (
  id bigint generated by default as identity primary key,
  usuario_id bigint references usuarios(id) on delete set null,
  usuario_nombre text not null,
  accion text not null,
  detalle text,
  fecha timestamptz not null default now()
);

create index if not exists idx_extintores_codigo on extintores (upper(codigo));
create index if not exists idx_inspecciones_extintor on inspecciones (extintor_id);
create index if not exists idx_auditoria_fecha on auditoria (fecha desc);

-- Nota sobre seguridad: este proyecto usa autenticación y autorización propias
-- (sesión + roles) en el backend de Express, que se conecta con la
-- service_role key (solo en el servidor, nunca en el navegador).
-- Por eso NO se habilita Row Level Security aquí: el control de acceso ya
-- ocurre en server.js antes de tocar la base de datos. Si en el futuro se
-- llamara a Supabase directamente desde el navegador, habría que habilitar
-- RLS y escribir políticas por rol.
--
-- Se desactiva explícitamente porque, si alguna de estas tablas se llegó a
-- tocar antes desde el Table Editor de Supabase (no el SQL Editor), la
-- interfaz activa RLS por defecto con un checkbox — y eso bloquea hasta al
-- propio backend con la service_role key mal configurada. Estas líneas
-- garantizan un estado conocido sin importar cómo se haya creado la tabla.
alter table usuarios disable row level security;
alter table extintores disable row level security;
alter table inspecciones disable row level security;
alter table auditoria disable row level security;
